### ISSUE TITLE
enhance_jit.py doesn't start to process the udio files

### ISSUE THREAD

**Issue by RadioAngurem** [Rikorose/clc-dns-challenge-2020#1]
Hi, I'm trying to test your model with some noise audios but I must be doing something grong because the
 script doesn't start to process the audio.

I put two noise wav-mono audios in a directory in Google drive and then I create a Google colab notebook:

!git clone https://github.com/Rikorose/clc-dns-challenge-2020.git

cd clc-dns-challenge-2020/

!pip install -r requirements.txt

cd clcnet-dns2020/

!python enhance_jit.py --verbose  --overwrite /content/clc-dns-challenge-2020/models/clc.pt '/content/drive/My Drive/AUDIO/AudioSucio' '/content/drive/My Drive/AUDIO/AudioProcesado' 

The last cell takes the model and the input/output folder:

>>Creating output folder /content/drive/My Drive/AUDIO/AudioProcesado
Processing audio files in folder /content/drive/My Drive/AUDIO/AudioSucio

But then doesn´t start to process the audio files inside the directory AudioSucio. The help command in enhance_jit.py say that the script takes the rest of parameters( NumWorkers, num_omp_threads, chunk_size with the default value). 

Thanks.

**Comment by Rikorose** [comment]
Hi, thanks for your interest in my repo.

Maybe it is a multi processing issue. Can you set num workers to 0?

You could also add some print statements to find the line where exactly the script hangs.

**Comment by RadioAngurem** [comment]
Hi, I've tried to set num_workers to 0 but then I get this error:

!python enhance_jit.py --verbose  --overwrite --num_workers 0 --num_omp_threads 1 '/content/clc-dns-challenge-2020/models/clc.pt' '/content/drive/My Drive/AUDIO/AudioSucio' '/content/clc-dns-challenge-2020/AudioProcesado'

Creating output folder /content/clc-dns-challenge-2020/AudioProcesado
Processing audio files in folder /content/drive/My Drive/AUDIO/AudioSucio
Traceback (most recent call last):
  File "enhance_jit.py", line 168, in <module>
    args.num_omp_threads,
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 167, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1

This is the entire Notebook:
![CCNet](https://user-images.githubusercontent.com/59012609/86394685-3c8e4480-bc9f-11ea-8def-39814e950b4d.jpg)

Thanks

**Comment by Rikorose** [comment]
OK then let default.

I am not familiar with colab. Could you help with debugging, e.g. add some print statements to find out where the script hangs? I was not able to reproduce your issue on my systems.

**Comment by RadioAngurem** [comment]
I've found the problem that cause the error:

In the line 158 of enhance_jit.py:
files = glob.glob(args.input_folder + "*.wav")

I have to put / at the end of the input file or edit enhance_jit.py and change the line to get 
files = glob.glob(args.input_folder + "/*.wav")

After that the program work correcty...and I hace tested it with a few noise audios and it works very good!!!. Now than I can use it I will test with more audios and more noises. I will send you my impression in a few days. Thanks

**Comment by Rikorose** [comment]
Thanks for finding this. I will push a fix to make this more robust next week.
